#pragma once
#define _CRT_SECURE_NO_DEPRECATE
#define WIN32_LEAN_AND_MEAN
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include <windowsx.h>
#include <strsafe.h>
#include <shobjidl.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <iomanip>
#include <map>
#include <cstring>
#include "resource.h"
#include "Files.h"
#include "Global.h"
#include "Winapi.h"
#include "Aura.h"
#include "Skill.h"
#include "MSG.h"
#include "SuperSoul.h"
#include "Stat.h"
